# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'RudderSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RudderSample
  pod 'RudderSDKCore', git: 'https://github.com/rudderlabs/rudder-sdk-ios.git', branch: 'objective-c-src-code' 

end
