name: Code Quality Checks(v2)
on:
  pull_request:
    branches: ['master-v2', 'develop-v2']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: Code Quality Checks(v2)
    runs-on: macOS-latest
    
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
      
      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build SDK(iOS)
        run: |
          xcodebuild build -scheme RudderSDK-iOS -workspace Rudder.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 13' | xcpretty
          
      - name: Build SDK(watchOS)
        run: |
          xcodebuild build -scheme RudderSDK-iOS -workspace Rudder.xcworkspace -destination 'platform=watchOS Simulator,name=Apple Watch Series 7 - 45mm' | xcpretty
      
      - name: Build SDK(tvOS)
        run: |
          xcodebuild build -scheme RudderSDK-iOS -workspace Rudder.xcworkspace -destination 'platform=tvOS Simulator,name=Apple TV' | xcpretty
          
      - name: Build SDK(macOS)
        run: |
          xcodebuild build -scheme RudderSDK-iOS -workspace Rudder.xcworkspace -destination 'platform=macOS,variant=Mac Catalyst' | xcpretty
          
      - name: Install Cocoapods
        run: gem install cocoapods
      
      - name: Execute pod lint
        run: pod lib lint --no-clean --allow-warnings
