name: Code Quality Checks
on:
  pull_request:
    branches: ['master', 'develop']
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  cancel_previous:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
    name: 'Cancel previous Code Quality Checks'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: styfle/cancel-workflow-action@3155a141048f8f89c06b4cdae32e7853e97536bc #v0.13.0
        with:
          workflow_id: ${{ github.event.workflow.id }}
          
  build:
    name: 'Code Quality Checks'
    needs: cancel_previous
    runs-on: macOS-latest
    
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout source branch
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      
      - name: Install xcpretty
        run: gem install xcpretty
        
      - name: Install Cocoapods
        run: gem install cocoapods
        
      - name: Pod install
        run: pod install --repo-update
        
      - name: Build SDK(iOS)
        run: |
          xcodebuild build -scheme Rudder_iOS -workspace Rudder.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty
          
      - name: Build SDK(watchOS)
        run: |
          xcodebuild build -scheme Rudder_watchOS -workspace Rudder.xcworkspace -destination 'platform=watchOS Simulator,name=Apple Watch Series 7 (45mm)' | xcpretty
      
      - name: Build SDK(tvOS)
        run: |
          xcodebuild build -scheme Rudder_tvOS -workspace Rudder.xcworkspace -destination 'platform=tvOS Simulator,name=Apple TV' | xcpretty
      
      - name: Execute pod lint
        run: pod lib lint --no-clean --allow-warnings
