name: Check PR title
on:
  pull_request:
    branches: ['main', 'develop']
    types: ['opened', 'reopened', 'edited', 'synchronize']

jobs:
  check_pr_title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#      - name: Check PR title
#        uses: aslafy-z/conventional-pr-title-action@v2.2.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Set Node 16
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16
#          cache: 'npm'
#
#      - name: Install action dependencies
#        env:
#          HUSKY: 0
#        run: |
#          cd ./.github/actions/check-pr-title
#          npm ci
#
#      - name: Check PR title
#        uses: ./.github/actions/check-pr-title
