name: Deploy to Cocoapods
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed
    
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/master') || github.event.pull_request.merged == true
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Publish to CocoaPod
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push --allow-warnings
