name: Deploy to Cocoapods(Manually)(v2)

on:
  workflow_dispatch

jobs:
  deploy-cocoapods-manual:
    name: Draft a new release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/master-v2')
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Publish to CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push --allow-warnings
