name: Manually deploy to Cocoapods

on:
  workflow_dispatch

jobs:
  deploy-cocoapods-manual:
    name: Manually deploy to Cocoapods
    runs-on: macOS-latest
    if: startsWith(github.ref, 'refs/heads/master')
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Publish to CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push --allow-warnings
