name: Beta deploy to Cocoapods

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  deploy-cocoapods-beta:
    name: Beta deploy to Cocoapods
    runs-on: macOS-latest
    if: startsWith(github.ref, 'refs/heads/beta-release/')
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout source branch
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Publish to CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push --allow-warnings
