name: CI
on:
  push:
    tags:
    - v1.*
    
jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push --allow-warnings
